// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon/miantivirus.png
var resourcePngData []byte
var resourcePng = &fyne.StaticResource{
	StaticName:    "icon/miantivirus.png",
	StaticContent: resourcePngData,
}
