// Copyright (C) 2024-2026 Murilo Gomes Julio
// SPDX-License-Identifier: GPL-2.0-only

// Site: https://www.bluice.com.br

package controls

import "github.com/bluiceoficial/blulang"

func LoadTranslations() {
	lang := blulang.GetLang()
	switch lang {
	case "pt":
		blulang.Set("Tools", "Ferramentas")
		blulang.Set("Options", "Opções")
		blulang.Set("About", "Sobre")
		blulang.Set("Check for Updates", "Verificar Atualizações")
		blulang.Set("Support MiAntivirus", "Apoie MiAntivirus")
		blulang.Set("About MiAntivirus", "Sobre MiAntivirus")
		blulang.Set("Files", "Arquivos")
		blulang.Set("Add File", "Adicionar Arquivo")
		blulang.Set("Open Files", "Abrir Arquivos")
		blulang.Set("Add Folder", "Adicionar Pasta")
		blulang.Set("Select Directory", "Selecione o Diretório")
		blulang.Set("Remove from List", "Remover da Lista")
		blulang.Set("Scan", "Escanear")
		blulang.Set("1) Detect PUA (Potentially Unwanted Application)", "1) Detectar PUA (Aplicativo Potencialmente Indesejado)")
		blulang.Set("2) Heuristic scanning", "2) Verificação heurística")
		blulang.Set("3) Scan hidden files", "3) Verificar arquivos ocultos")
		blulang.Set("4) Check symbolic files", "4) Verificar arquivos simbólicos")
		blulang.Set("5) Check symbolic folders", "5) Verificar pastas simbólicas")
		blulang.Set("6) Scan compressed files", "6) Escanear arquivos compactados")
		blulang.Set("7) Scan Email", "7) Escanear e-mail")
		blulang.Set("File Size for Scanning", "Tamanho do arquivo para escaneamento")
		blulang.Set("Ignore Folders", "Ignorar pastas")
		blulang.Set("Add", "Adicionar")
		blulang.Set("Remove", "Remover")
		blulang.Set("Ignore Files", "Ignorar arquivos")
		blulang.Set("Open File", "Abrir arquivo")
		blulang.Set("General", "Em geral")
		blulang.Set("Ignore", "Ignorar")
		blulang.Set("Save", "Salvar")
		blulang.Set("Check:", "Verificar:")
		blulang.Set("Scanning...", "Escaneando...")
		blulang.Set("Generate Report", "Gerar Relatório")
		blulang.Set("Save File", "Salvar Arquivo")
		blulang.Set("Date: %v\n\n", "Data: %v\n\n")
		blulang.Set("Remove File", "Remover Arquivo")
		blulang.Set("Removing selected files...", "Removendo arquivos selecionados...")
		blulang.Set("Deleted", "Excluído")
		blulang.Set("Cancel", "Cancelar")
		blulang.Set("Update Database", "Atualizar Banco de Dados")
		blulang.Set("Checking for updates...", "Verificando atualizações...")
		blulang.Set("Finish", "Concluído")
		blulang.Set("No viruses found!", "Nenhum vírus encontrado!")
	case "es":
		blulang.Set("Tools", "Herramientas")
		blulang.Set("Options", "Opciones")
		blulang.Set("About", "Acerca de")
		blulang.Set("Check for Updates", "Buscar actualizaciones")
		blulang.Set("Support MiAntivirus", "Soporte MiAntivirus")
		blulang.Set("About MiAntivirus", "Acerca de MiAntivirus")
		blulang.Set("Files", "Archivos")
		blulang.Set("Add File", "Agregar archivo")
		blulang.Set("Open Files", "Abrir archivos")
		blulang.Set("Add Folder", "Agregar carpeta")
		blulang.Set("Select Directory", "Seleccionar directorio")
		blulang.Set("Remove from List", "Eliminar de la lista")
		blulang.Set("Scan", "Escanear")
		blulang.Set("1) Detect PUA (Potentially Unwanted Application)", "1) Detectar PUA (Aplicación Potencialmente no Deseada)")
		blulang.Set("2) Heuristic scanning", "2) Escaneo heurístico")
		blulang.Set("3) Scan hidden files", "3) Escanear archivos ocultos")
		blulang.Set("4) Check symbolic files", "4) Verificar archivos simbólicos")
		blulang.Set("5) Check symbolic folders", "5) Verificar carpetas simbólicas")
		blulang.Set("6) Scan compressed files", "6) Escanear archivos comprimidos")
		blulang.Set("7) Scan Email", "7) Escanear correo electrónico")
		blulang.Set("File Size for Scanning", "Tamaño de archivo para escanear")
		blulang.Set("Ignore Folders", "Ignorar carpetas")
		blulang.Set("Add", "Agregar")
		blulang.Set("Remove", "Eliminar")
		blulang.Set("Ignore Files", "Ignorar archivos")
		blulang.Set("Open File", "Abrir archivo")
		blulang.Set("General", "General")
		blulang.Set("Ignore", "Ignorar")
		blulang.Set("Save", "Ahorrar")
		blulang.Set("Check:", "Controlar:")
		blulang.Set("Scanning...", "Exploración...")
		blulang.Set("Generate Report", "Generar informe")
		blulang.Set("Save File", "Guardar archivo")
		blulang.Set("Date: %v\n\n", "Fecha: %v\n\n")
		blulang.Set("Remove File", "Eliminar archivo")
		blulang.Set("Removing selected files...", "Eliminando archivos seleccionados...")
		blulang.Set("Deleted", "Eliminado")
		blulang.Set("Cancel", "Cancelar")
		blulang.Set("Update Database", "Actualizar base de datos")
		blulang.Set("Checking for updates...", "Buscando actualizaciones...")
		blulang.Set("Finish", "Finalizar")
		blulang.Set("No viruses found!", "¡No se encontraron virus!")
	}
}

func T(key string, args ...interface{}) string {
	return blulang.T(key, args...)
}
